### ISSUE TITLE
rename repo to yazelix

### ISSUE THREAD

**Issue by luccahuguet** [luccahuguet/zellij#13]
it will hurt out-of-the-boxness because you wont be able to just clone the repo but something feels off about this repo being called zellij

**Comment by schlich** [comment]
i actually appreciated the shortcut, if you do change this i'd suggest keeping the same workflow and encouraging folks to git clone with the target directory specified e.g. `git clone https://github.com/luccahuguet/yazelix $XDG_CONFIG_HOME/zellij`

**Comment by luccahuguet** [comment]
Thank you for the input, @schlich 

the solution I envisioned is a bit different, I'd suggest you take a look at the v4 branch README, in the installing instructions: https://github.com/luccahuguet/zellij/tree/v4#instructions-to-set-it-up

What do you think about this new workflow?

**Comment by luccahuguet** [comment]
v4 actually has already been ready for release since a week ago

what was hard was installing a screenkey alternative to show my screenstrokes as I record my screen to show people how the v4 works, and after I did get it done, I had other priorities to attend to

but you can run the v4 branch if you want (just dont announce it on reddit lol) 

i will be doing it in the following days

**Comment by schlich** [comment]
I still think it would be easier to just rename the folder as you clone it!  that way you dont need to specify custom config and layout directories.

(in case it is unclear what i'm talking about, adding a second argument to the `git clone` command (or `gh repo clone` if you're using the cli) just renames the cloned repo to that second argument.  So you can name the repo `yazelix` but give folks a way to have the repo land in `~/.config/zellij` which definitely simplified things.

just my two cents!

**Comment by luccahuguet** [comment]
> I still think it would be easier to just rename the folder as you clone it!  that way you dont need to specify custom config and layout directories.
> 
> (in case it is unclear what i'm talking about, adding a second argument to the `git clone` command (or `gh repo clone` if you're using the cli) just renames the cloned repo to that second argument.  So you can name the repo `yazelix` but give folks a way to have the repo land in `~/.config/zellij` which definitely simplified things.
> 
> just my two cents!

Thanks, this is helpful

**Comment by luccahuguet** [comment]
solved by #16
