### ISSUE TITLE
hardcoded username in layouts/yazelix.kdl

### ISSUE THREAD

**Issue by nyawox** [luccahuguet/zellij#4]
firstly thank you for creating such a wonderful work.
your username is hardcoded in layouts/yazelix.kdl ([link](https://github.com/luccahuguet/zellij/blob/8eb552cfa7fb73376a710c4922047092b5be9359/layouts/yazelix.kdl#L14)), making not able to install successfully just by following instructions.

**Comment by orual** [comment]
Yeah, noticed this as well. Easy change would be to just refer to `~/.config/...` as you've done elsewhere.

**Comment by luccahuguet** [comment]
oh wow, I should've seen that, hahaha, my bad

thank you, wonderful people for this very important fix!

**Comment by luccahuguet** [comment]
ive pushed the fix to main. Solved by nyawox and orual
