### ISSUE TITLE
Opening new files

### ISSUE THREAD

**Issue by peteringram0** [luccahuguet/zellij#5]
When opening new files from the yazi sidebar does it open the file in a new helix instance or open the buffer within the same helix instance?

Thanks

**Comment by luccahuguet** [comment]
hi there, thanks for taking interest in the project

it opens in a new helix instance, within a new zellij pane
when you close this helix instance, the pane also closes

it's like a "helix-only" pane

for opening in the same buffer, you can check out this other project that makes use of tmux, wezterm, helix, and a bunch of shell scripting: https://github.com/quantonganh/helix-wezterm
